### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by crisjff** [sehaas/ha_hisense_tv#1]
Hello, thank you for your work. As I was installing I got this:

Logger: homeassistant.loader
Source: loader.py:786
First occurred: 01:32:49 (1 occurrences)
Last logged: 01:32:49

No 'version' key in the manifest file for custom integration 'hisense_tv'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'hisense_tv'

**Comment by sehaas** [comment]
Thanks for reporting. Fixed.
