### ISSUE TITLE
Unable to control (Acting read only)

### ISSUE THREAD

**Issue by tungmeister** [sehaas/ha_hisense_tv#10]
Hi, everything appears to be working perfectly other than I'm unable to turn off my device (Hisense Laser TV) it will power on fine but turning off does nothing, toggling the power switch will also just turn straight back on. Powering on works fine.

EDIT: actually I've just done some more testing and I've totally lost the ability to control the TV in any way - volume control, source etc don't work however they do update perfectly I If I use the Phone app or remote. I Have no control from within Home assistant?

**Comment by tungmeister** [comment]
I've done some further testing and it doesn't seem to be an MQTT issue - I can still control the TV from home assistant by manually sending messages:
![image](https://user-images.githubusercontent.com/127809/147494859-d52aa9bb-76c7-498e-826b-32feeb3697b5.png)
(in the example above I'd reset all the configuration and setup a topic other than the default Hisense one hence the use of living room tv. I'm also imitating my phone app. 
It seems as though the integration is subscribing to the state topic hence getting the input etc but not actually trying to send any commands (or if it does they're going to the wrong place). Watching MQTT explorer nothing changes when trying to issue commands from the media_player controls.

EDIT: I've monitored mosquitto via MQTT explorer and don't see any topic changes at all when attempting to issue commands so I think the problem definitely lies with the integration.

**Comment by sehaas** [comment]
It sounds like your prefix setup may not be correct.
Did you connect with the MQTT explorer to the broker of the TV or of HA?
Can you post your bridge config (without the password)?

**Comment by tungmeister** [comment]
I've tried it with the default prefix (which was working, it stopped without any changes) and the one I'm using now. 
I connected MQTT explorer to both the TV and HA. When trying to issue commands from the media_player in HA there were no changes on either of the brokers. It was only when I tried with my phone that I could see changes on the TV. 

I'm currently running with the livingroom_tv prefix which is working in the sense that status info is still updating and I can still control by my workaround solution of an mqtt switch configured the same as the above screenshot. (only changed from the default prefix just to see if it made a difference)

I can't see how the below config wouldn't be working as I'm 100% connecting to the TV broker without issue.

```
connection hisensemqtt
address 10.0.0.30:36669
username hisenseservice
password *********
clientid HomeAssistant
bridge_cafile /share/mosquitto/ssl/hisense.crt
bridge_certfile /share/mosquitto/ssl/rcm_certchain_pem.pem
bridge_keyfile /share/mosquitto/ssl/rcm_pem_privkey.key
bridge_insecure true
bridge_tls_version tlsv1.2
try_private false
start_type automatic
topic /remoteapp/# both 0 livingroom_tv ""
```

**Comment by NeeeeB** [comment]
I do have the exact same problem, with the same configuration.
Prefix is the default one (hisense).
If it was a prefix problem, tv state would not update in HA.
Volume, source, state etc... update perfectly on the HA UI, but trying to control the TV from HA has absolutely no effect.
Only Switching the TV on works, like @tungmeister but I'm pretty sure it is because it uses wake on lan and not MQTT.
At this point, the integration is of no use...

TV is 55U7QF.

Additional question : what MAC address is it expecting ? the TV one ? the phone's one where the remote app is on ? that is totally unclear...

**Comment by tungmeister** [comment]
@NeeeeB Yeah it's turning on due to the wake on lan. It's the mac address of the TV hence your wake on lan working. I use it as part of a universal media player. The main issue I was having was the lack of ability to turn it off hence my workaround above - the mac address in my workaround switch is the mac address of my phone as that's what's authorised on the TV. based on my logging it doesn't appear that the integration is publishing any MQTT messages as nothing was showing on either broker.

**Comment by NeeeeB** [comment]
![image](https://user-images.githubusercontent.com/12588210/147575366-ea3dcb4a-0e0a-495b-92d4-7d9234600ed5.png)
I'm no Python expert but isn't that "%s" supposed to be replaced with something in the MQTT command sent ?
When I have a look here:
https://github.com/Krazy998/mqtt-hisensetv
That %s seems to be replaced with something...
In the language I use, that kind of %s thing expects an argument to be passed to replace it.

**Comment by tungmeister** [comment]
Yeah, I would imagine the %s is replaced with whatever the integration identified itself as when initially registering with the TV. The same as the MAC address of your phone with the app. Even if this wasn't being substituted though I would still expect to see the message on one of the brokers, even if the topic was incorrect. The fact that I don't see any messages on either leads me to think that the integration isn't publishing any of the commands at all (based on my limited MQTT knowledge)

**Comment by sehaas** [comment]
The `%s` is replaced in the called method. It uses a custom key which is authorized with the TV during setup (where you have to enter the PIN code displayed on the TV)

The integration is subscribing and publishing to MQTT. Which HA version are you using? I still have `2021.11.5` and it's working just fine.
Have you checked the release notes, if there are any breaking changes related to MQTT in the latest versions?

**Comment by sehaas** [comment]
Could be related to this https://github.com/home-assistant/core/pull/58441 ?

**Comment by NeeeeB** [comment]
I don't know, you are the developper ^^
I'm on the latest version available btw, 2021.12.6, and I had the problem too with 2021.12.0

EDIT: your solution seems to be here.
https://github.com/ThermIQ/thermiq_mqtt-ha/issues/4#issue-1038158182

**Comment by tungmeister** [comment]
That will be the issue. I've just been doing some debug logging and can see:
```
2021-12-28 17:12:23 DEBUG (MainThread) [custom_components.hisense_tv.helper] _out_topic: livingroom_tv/remoteapp/tv/remote_service/HomeAssistant/actions/sendkey
```
this is when pressing the power button on the media_player, after though no MQTT message is published.

compared to when I use my manual button you can see a message is actually published:
```
2021-12-28 17:11:08 DEBUG (MainThread) [homeassistant.components.mqtt] Transmitting message on livingroom_tv/remoteapp/tv/remote_service/1A:E0:6B:F6:5C:2F$normal/actions/sendkey: 'KEY_POWER', mid: 531
```
I've confirmed that the first topic does work fine if I manually publish it.

**Comment by sehaas** [comment]
I pushed a possible fix (#11), but I can't test it right now. If someone can confirm that the fix is working, I'll release a new version. Otherwise you have to wait until I upgrade my setup - which could take a while 😁

**Comment by NeeeeB** [comment]
I would happily test it, but I don't know how to do...
I installed your integration with HACS

**Comment by tungmeister** [comment]
@sehaas it's working fine for the most part however the browse media button results in an error (not that it's a feature I'd ever use)
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1168, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/hisense_tv/media_player.py", line 566, in async_browse_media
    return await self._build_library_node()
  File "/config/custom_components/hisense_tv/media_player.py", line 490, in _build_library_node
    payload = json.loads(msg[0].payload)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Unrelated note but what's holding you back from updating to the 2021.12 builds?

**Comment by sehaas** [comment]
Thanks for the feedback. I'll recheck that part.

Ad update: why should I waste time to upgrade a system that is working completely fine if there isn't any security consern? Doing an update right (reading release notes, checking custom configurations/integrations for compatibility, etc.) is more work than just increasing the version number.

**Comment by sehaas** [comment]
@tungmeister I don't think that the problem with the browse button is related.
Could you manually publish this topic `livingroom_tv/remoteapp/tv/platform_service/HomeAssistant/actions/getchannellistinfo`
and post the result of `livingroom_tv/remoteapp/mobile/HomeAssistant/platform_service/data/getchannellistinfo` ?

This should return something like this (my TV is connected to a twin-satellite receiver):
```json
[{
	"list_name":	"ASTRA1 19.2°E",
	"list_para":	"sl5824ec82-db05-4acf-85d1-404b560ac198",
	"list_version":	"5",
	"dtv_flag":	1
}, {
	"list_name":	"Hot Bird 13°E",
	"list_para":	"sl3bd84cb6-680d-4113-ad06-1ed8e1c62707",
	"list_version":	"2",
	"dtv_flag":	1
}]
```

**Comment by wifi75** [comment]
I did not understand what needs to be done to solve the problem ... can you give me some help?
I have the bridge on home assistant.

**Comment by NeeeeB** [comment]
@wifi75 you have to wait until @sehaas releases a new version with the fix included.
Or you can modify the files manually in your installation.
See https://github.com/sehaas/ha_hisense_tv/pull/11 to know what files need to be replaced/modified but if you're not used to such modifications, I strongly suggest that you wait for the update.

**Comment by tungmeister** [comment]
If you just download the zip of the mqtt fix branch
https://github.com/sehaas/ha_hisense_tv/tree/fix_mqtt_api_changes and replace the contents of your hisense_tv directory in your custom_compments folder in your config directory you'll be good to go.

**Comment by tungmeister** [comment]
@sehaas There doesn't seem to be any data In that topic (nothing showing in mqtt explorer anyway) - I don't actually use the TV tuners in mine though as I don't really watch live TV so would that be the issue? Though I was under the impression that Apps should be returned?

**Comment by sehaas** [comment]
Thanks for the feedback.
The Media-Explorer shows both: TV Channels (grouped by the satellite receiver) and applications.
I'll handle this case as well and will release a new version.

**Comment by tungmeister** [comment]
It looks like the remotenow app requests gettvinfo which returns a load of data:
![image](https://user-images.githubusercontent.com/127809/147741877-6d1c49f6-b518-4101-8fd7-cdf973261000.png)
EDIT: Ah, I'm assuming you publish both messages to get the channel info and app info but as I don't use the tuner no data is returned for the getchannellist info and there's nothing in place at the moment to handle this being null?

**Comment by wifi75** [comment]
> Thanks for the feedback. The Media-Explorer shows both: TV Channels (grouped by the satellite receiver) and applications. I'll handle this case as well and will release a new version.


so you can confirm that at the moment only the switching on and off works?

**Comment by sehaas** [comment]
New version was released. Thanks for the support.

**Comment by nepozs** [comment]
It looks like wrong version number (21.11.28 instead of 21.12.28).

**Comment by sehaas** [comment]
> It looks like wrong version number (21.11.28 instead of 21.12.28).

Thanks. Fixed.
