### ISSUE TITLE
no Source TV, HDMI, Apps

### ISSUE THREAD

**Issue by wifi75** [sehaas/ha_hisense_tv#12]
CIao I don't know why but I no longer see the list of TV channels, sources and media.
how come?

**Comment by sehaas** [comment]
Maybe related to issue #10 and PR #11

Can you provide more information about your setup. Which version? Related logs?

**Comment by wifi75** [comment]
hello, I integrated it with HA, what log do you need?

**Comment by wifi75** [comment]
![image](https://user-images.githubusercontent.com/31816231/147647780-a1be6cb4-638c-42bc-a466-09c2f1500bee.png)

then 

![image](https://user-images.githubusercontent.com/31816231/147647851-9293ee48-d54f-4e23-a52a-7b71295fd352.png)

**Comment by sehaas** [comment]
Please recheck with new release.

Otherwise the logs can be found under `Configuration` => `Settings` => `Logs`

**Comment by sehaas** [comment]
@wifi75 is it working? If so, please close the bug.

**Comment by sehaas** [comment]
no feedback - closing the issue
