### ISSUE TITLE
Hisense 50" QLED 4K 2021 50E78GQ

### ISSUE THREAD

**Issue by vix66** [sehaas/ha_hisense_tv#13]
I try with this model, Hisense 50" QLED 4K 2021 50E78GQ, but no work !

**Comment by sehaas** [comment]
Please provide more information. 
Does your TV have an integrated MQTT broker and does your bridge setup work?
What version of HA are you using?
Provide logs from HA or your MQTT broker.

**Comment by vix66** [comment]
Hi,

ha: the last

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] mosquitto.sh: executing... 
[11:46:25] INFO: Certificates found: SSL is available
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:46:26] INFO: Starting NGINX for authentication handling...
[11:46:26] INFO: Starting mosquitto MQTT broker...
1641725186: Loading config file /share/mosquitto/hisense.conf
1641725186: mosquitto version 1.6.12 starting
1641725187: |-- *** auth-plug: startup
[11:46:28] INFO: Successfully send discovery information to Home Assistant.
[11:46:29] INFO: Successfully send service information to the Supervisor.
1641725186: Config loaded from /etc/mosquitto/mosquitto.conf.
1641725186: Loading plugin: /usr/share/mosquitto/auth-plug.so
1641725187:  ├── Username/password checking enabled.
1641725187:  ├── TLS-PSK checking enabled.
1641725187:  └── Extended authentication not enabled.
1641725187: Opening ipv4 listen socket on port 1883.
1641725187: Opening ipv6 listen socket on port 1883.
1641725187: Opening websockets listen socket on port 1884.
1641725187: Opening ipv4 listen socket on port 8883.
1641725187: Opening ipv6 listen socket on port 8883.
1641725187: Opening websockets listen socket on port 8884.
1641725187: Warning: Mosquitto should not be run as root/administrator.
1641725187: Connecting bridge hisensemqtt (192.168.0.118:36669)
1641725187: mosquitto version 1.6.12 running
1641725187: New connection from 127.0.0.1 on port 1883.
1641725187: Socket error on client <unknown>, disconnecting.
1641725187: Socket error on client local.HomeAssistant, disconnecting.

**Comment by sehaas** [comment]
Logs don't show anything strange.
What isn't working for you? You need to describe what are you trying to do and what is working or not.
Are you stuck in the setup process? Could you register the TV in HA (enter PIN code shown on TV)?
