### ISSUE TITLE
State defaults to "on" at Hass startup

### ISSUE THREAD

**Issue by tungmeister** [sehaas/ha_hisense_tv#14]
With the latest version, every time I restart Hass the TV's state is set to "on" regardless of it's actual state. This wasn't happening previously.

**Comment by sehaas** [comment]
Please check your MQTT broker, if any Hisense-related topic has the `retained` flag set. If this is the case, every client (in your case, your restarted HA) will get the last value stored by the broker.

The integration sets the TV to "on" if any related MQTT message has arrived.

**Comment by tungmeister** [comment]
Clearing all the topics and restarting seems to have fixed it. There was probably something left over from all the testing with the issues from the previous build. Thanks
