### ISSUE TITLE
Unable to load configuration wizard

### ISSUE THREAD

**Issue by yamazakitouma** [sehaas/ha_hisense_tv#15]
After installing with HACS, rebooting and adding in the integration, it prompts "Unable to load configuration wizard"

**Comment by yamazakitouma** [comment]
Invalid config
The following integrations and platforms could not be set up:

mqtt
Please check your config and logs.

**Comment by sehaas** [comment]
Do you have a working Mqtt setup for your HA? Did you follow the [instructions](https://github.com/sehaas/ha_hisense_tv/blob/main/README.md#mqtt)?
