### ISSUE TITLE
Does anybody know where I might learn how to generate the cert files?

### ISSUE THREAD

**Issue by dustinlocke** [sehaas/ha_hisense_tv#16]
The config mentions three files:
bridge_cafile hisense_ca.pem
bridge_certfile hisense_client.pem
bridge_keyfile hisense_client.key

Can somebody point me in the direction of how to generate these files?

I've dug through the links provided, but the ones I can find use a hisense.crt file and I'm not smart enough to know if/how it translates.

**Comment by sehaas** [comment]
You can't generate them yourself. The client certificate must be singed by Hisense.

As I stated in the readme I won't add or link to them for legal reasons.
If you dig through the Home Assistant forum, you will find a repository containing the right files.

**Comment by dustinlocke** [comment]
Thank you for the explanation!
