### ISSUE TITLE
Integration installation hangs indefinitely on install

### ISSUE THREAD

**Issue by UncleLeoTheDad** [sehaas/ha_hisense_tv#17]
After I install this via HACS, reboot and then install the integration, I am prompted for the MAC address of the TV, which I provide, click "Submit" and then this screen starts spinning.  I left it to run for 12 hours or so.  I'm guessing it's stuck.
![image](https://user-images.githubusercontent.com/141352/151365006-0bb96392-d8b9-44be-b495-a26f4d4f8c97.png)

I've done the following:
- Ensured I installed MQTT correctly.  I was able to verify it is up and running: 
![image](https://user-images.githubusercontent.com/141352/151365237-bdb2a782-738e-4593-b13d-f08eac3ea9f2.png)
- I've tried restarting HA and going through the install process again, but the results are the same.

Is there anything I can enable on my side to provide more debugging info?

Thanks!

**Comment by sehaas** [comment]
Did you setup the bridge between the TV and your MQTT broker?

**Comment by n-stein** [comment]
Try a different browser. I hit this same issue when using Firefox, but using Edge/Chrome I was able to set it up successfully. 

For me the bridge was set up properly and when submitting my MAC during the HACS install the TV would show the 4 digit link code, but Home Assistant never opened the user input form for me to type it in, just got the indefinite loading screen you are experiencing. Using Edge the user input form was correctly displayed and the linking completed.

**Comment by UncleLeoTheDad** [comment]
> Did you setup the bridge between the TV and your MQTT broker?

Probably not.  You are referring to this section?  
![image](https://user-images.githubusercontent.com/141352/153207535-0cc6f9b0-4825-49de-b12a-038b21eb80f1.png)


I'm unfortunately not well versed in MQTT, so I had a hard time following that piece.  Where does that configuration go in order to create the bridge?  Is that added to the add-on's configuration or somewhere else?

Sorry if this is obvious and I'm somehow missing it!

**Comment by UncleLeoTheDad** [comment]
@n-stein : I was using firefox.  @sehaas 's reply makes me think I am missing a step as well, but I'll be sure to try chrome vs firefox based on your reply.  Thanks!

**Comment by n-stein** [comment]
> Where does that configuration go in order to create the bridge? Is that added to the add-on's configuration or somewhere else?

Assuming you are using the Mosquitto Broker addon within Home Assistant, in the share/ directory create a sub directory called "mosquitto". Then within share/mosquitto/ create a new file called "hisense.conf" that contains the bridge configuration and restart your Home Assistant mosquitto broker addon.

**Comment by UncleLeoTheDad** [comment]
@n-stein : thanks, this helps.  I'm currently working through this.  Having trouble connecting to my H8G, so I tried through MQTT-Explorer and through the python script someone created here:
https://github.com/Krazy998/mqtt-hisensetv/issues/2

Unfortunately neither are working ATM.  Once I can confirm I can actually connect, I'll resume trying to get this integration added.

**Comment by n-stein** [comment]
Check your certificate configuration. I have a U6G, but your H8G might be similar. In my case I didn't need the bridge_certfile and bridge_keyfile parameters, just needed to extract the certificate using openssl and use it as bridge_cafile. I found tiagofreire-pt's writeup here https://github.com/tiagofreire-pt/Home_Assistant_Hisense_TV to be very helpful. 

Then your config looks like:

connection hisense
address <TV_IP_ADDRESS>:36669
remote_username hisenseservice
remote_password multimqttservice
remote_clientid HomeAssistant
bridge_tls_version tlsv1.2
bridge_cafile /ssl/hisense.crt
bridge_insecure true
start_type automatic
try_private true
topic /remoteapp/# both 0 <MQTT_PREFIX> ""

**Comment by UncleLeoTheDad** [comment]
This was helpful, @n-stein!  I think the bridge is set up correctly now.  Here is the log output:
<img width="967" alt="image" src="https://user-images.githubusercontent.com/141352/153936300-a44214c6-3d88-4702-89a7-e4db6e0ea42b.png">

I was then able to get the pin prompt and get this all set up.  Thanks!

**Comment by UncleLeoTheDad** [comment]
Okay, I spoke too soon, @n-stein.  When I go to view the TV's state I see this:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/141352/153938477-5dd82db9-7e25-4e07-ac65-e1cef988a5f4.png">

The entities look like this:
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/141352/153938514-cd400e9a-4113-4d96-9094-7ecd4c0ecf11.png">

The TV is currently on, so I'm not sure why the switch appears off.  When I try to turn it off/on via , nothing happens.

I tried restarting HA and uninstalling/reinstalling the integration.  Any other ideas?

**Comment by UncleLeoTheDad** [comment]
Spoke too soon once again!  Suddenly now it is appearing to be on, so must have been some delay.  The button in HA works.

**Comment by McFarTech** [comment]
I am facing the exact same issue. I have tried different browsers on different computers and all give me the same result. 

Does the MAC address format matter eg all lower case or upper case with : 

Can anyone help where i can troubleshoot this further? 


`[11:20:44] INFO: Starting NGINX for authentication handling...
[11:20:45] INFO: Starting mosquitto MQTT broker...
1655374845: Loading config file /share/mosquitto/hisense.conf
1655374845: Warning: Bridge hisense using insecure mode.
1655374845: Warning: Mosquitto should not be run as root/administrator.
[11:20:45] INFO: Successfully send discovery information to Home Assistant.
[11:20:45] INFO: Successfully send service information to the Supervisor.
1655374845: mosquitto version 2.0.11 starting
1655374845: Config loaded from /etc/mosquitto/mosquitto.conf.
1655374845: Loading plugin: /usr/share/mosquitto/go-auth.so
1655374845:  ├── Username/password checking enabled.
1655374845:  ├── TLS-PSK checking enabled.
1655374845:  └── Extended authentication not enabled.
1655374845: Opening ipv4 listen socket on port 1883.
1655374845: Opening ipv6 listen socket on port 1883.
1655374845: Opening websockets listen socket on port 1884.
1655374845: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655374845: mosquitto version 2.0.11 running
1655374845: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655374845: Client local.HomeAssistant closed its connection.
1655374845: New connection from 127.0.0.1:52400 on port 1883.
1655374845: Client <unknown> closed its connection.
1655374845: New connection from 172.30.32.1:42133 on port 1883.
1655374845: New client connected from 172.30.32.1:42133 as 7zQnwcEXBpW9sTQE3atXV5 (p2, c1, k60, u'homeassistant').
1655374846: New connection from 172.30.33.2:58270 on port 1883.
1655374846: New client connected from 172.30.33.2:58270 as mqttjs_7c86a6b5 (p2, c1, k60, u'addons').
1655374850: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655374850: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655374850: Client local.HomeAssistant closed its connection.
1655374853: New connection from 172.30.32.2:45188 on port 1883.
1655374853: Client <unknown> closed its connection.
1655374859: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655374859: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655374859: Client local.HomeAssistant closed its connection.
1655374872: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655374872: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655374872: Client local.HomeAssistant closed its connection.
1655374889: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655374889: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655374889: Client local.HomeAssistant closed its connection.
1655374920: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655374920: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655374920: Client local.HomeAssistant closed its connection.
1655374951: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655374951: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655374951: Client local.HomeAssistant closed its connection.
1655374973: New connection from 172.30.32.2:58420 on port 1883.
1655374973: Client <unknown> closed its connection.
1655374982: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655374982: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655374982: Client local.HomeAssistant closed its connection.
1655375013: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655375013: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655375013: Client local.HomeAssistant closed its connection.
1655375040: Client 7zQnwcEXBpW9sTQE3atXV5 closed its connection.
1655375044: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655375044: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655375044: Client local.HomeAssistant closed its connection.
1655375050: New connection from 172.30.32.1:49909 on port 1883.
1655375050: New client connected from 172.30.32.1:49909 as 7cardnvwSHvQLlLi2PAKgd (p2, c1, k60, u'homeassistant').
1655375075: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655375075: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655375075: Client local.HomeAssistant closed its connection.
1655375093: New connection from 172.30.32.2:59306 on port 1883.
1655375093: Client <unknown> closed its connection.
1655375106: Connecting bridge (step 1) hisense (172.16.17.46:36669)
1655375106: Connecting bridge (step 2) hisense (172.16.17.46:36669)
1655375106: Client local.HomeAssistant closed its connection.
1655375132: Connecting bridge (step 1) hisense (172.16.17.46:36669)`
