### ISSUE TITLE
TV status after Home Assistant reboot

### ISSUE THREAD

**Issue by andriuskr** [sehaas/ha_hisense_tv#18]
After rebooting Home Asisstant TV is shown as ON. Does not respond to OFF/ON button. Turning ON tv manually solves the problem.

**Comment by sehaas** [comment]
Please see #14 and check for retained values on your MQTT broker.

**Comment by andriuskr** [comment]
Deleted this topic from broker, rebooted. Has retained flag. After HA reboot it still show TV as on...
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/13429780/151852708-3d3d8634-c03b-4188-838a-712d6e9561d9.png">

**Comment by sehaas** [comment]
Maybe the broker of the TV has also the retained flag set?
It would be possible to ignore messages having the retained flag set, but I don't know if this breaks anything else.

**Comment by andriuskr** [comment]
> 
Yes, correct. TV broker also has retained flag.

**Comment by sakowicz** [comment]
I can confirm that it happens also to me for last few weeks. Retained flag is on.

**Comment by sehaas** [comment]
Only for the `state` topic or others as well?

Have you tried to delete the flag on both brokers?

**Comment by sehaas** [comment]
I can reproduce the behaviour. My code already handles (ignores) retained messages, but the check isn't working any more.
It looks like the boolean flag was changed to a number (0 & 1). Let's see if this is a bug in HA or if missed some breaking API changes.

**Comment by sehaas** [comment]
Fixed. Retained messages will be ignored.
