### ISSUE TITLE
Hisense Series 6 and no-SSL, no auth

### ISSUE THREAD

**Issue by chadodes** [sehaas/ha_hisense_tv#19]
Hi Folks, I have a sharp HU43A6107UW running build K0829 on it.
This is a 43" 4K HDR set that is a Hisense series 6 and responds to a series 6 MQTT remoteapp subscriptions and posts.

The thing I am trying to configure out is the option to run without needing authorization and without SSL.

When I was using newAm's build (both based off the same code?) I could use the "--no-ssl " optional argument.
While in here I would assume this is needing to be done in the broker config, but I can't seem to figure it out.
I have removed all the broker config lines in regards to ssl and certificates, but I still get a loop or connect/disconnects.

Has anyone else figured out how to do this through the MQTT broker yet?
Thanks!

**Comment by bengAThome** [comment]
Hi there, when you say "responds to a series 6 MQTT", do you mean you have this working in MQTT explorer for example?

**Comment by sehaas** [comment]
Try to remove those lines:
```
bridge_tls_version tlsv1.2
bridge_cafile hisense_ca.pem
bridge_certfile hisense_client.pem
bridge_keyfile hisense_client.key
```
I couldn't test it as mine requires SSL.
