### ISSUE TITLE
not connect

### ISSUE THREAD

**Issue by wifi75** [sehaas/ha_hisense_tv#2]
Hello after insert data from HA:
![image](https://user-images.githubusercontent.com/31816231/118303687-05efa000-b4e6-11eb-90d3-ac5e6224abe4.png)
the circle always turns and does not finish the setup, why?
![image](https://user-images.githubusercontent.com/31816231/118303865-3a635c00-b4e6-11eb-9bc8-1db93b1ee9f1.png)

In HA, in which folder should the certificates be copied?

**Comment by sehaas** [comment]
Have you configured the MQTT bridge?
There you need the certificates. See https://github.com/sehaas/ha_hisense_tv#mqtt

**Comment by wifi75** [comment]
I have broker already installed:
![image](https://user-images.githubusercontent.com/31816231/118306162-4f8dba00-b4e9-11eb-8b1f-aaab6cecba12.png)

**Comment by wifi75** [comment]
sorry what do you mean this below?

![image](https://user-images.githubusercontent.com/31816231/118308346-1f93e600-b4ec-11eb-8ac9-c8a3548b54d1.png)

**Comment by wifi75** [comment]
then in zip file there is two certificate:
rcm_certchain_pem.cer
rcm_pem_privkey.pkcs8

your configuration for mqtt bridge it is like below:

connection hisense
address <TV_IP_ADDRESS>:36669
username <HISENSE_MQTT_USERNAME>
password  <HISENSE_MQTT_PASSWORD>
clientid HomeAssistant
bridge_tls_version tlsv1.2
bridge_cafile hisense_ca.pem
bridge_certfile hisense_client.pem
bridge_keyfile hisense_client.key
bridge_insecure true
start_type automatic
try_private true
topic /remoteapp/# both 0 <MQTT_PREFIX> ""

what is the correct line for certicate?

certificate do I have to copy them where?

**Comment by sehaas** [comment]
Just from the names I suggest you try:
`rcm_certchain_pem.cer` => `hisense_client.pem` and `rcm_pem_privkey.pkcs8` => `hisense_client.key`

I have my client certificate and key next to the `mosquitto.conf` file with the bridge configuration

**Comment by sehaas** [comment]
It looks like you were able to establish a connection, so I'll close this issue.
