### ISSUE TITLE
MQTT bridge not connecting to 55U7G (Australian version) 

### ISSUE THREAD

**Issue by bengAThome** [sehaas/ha_hisense_tv#20]
G'day,
Thanks a lot for your work on this, I got a long way by reading and interpreting the instructions.
However, I have hit a roadblock getting the HA Mosquito bridge functioning.
The Mosquito log shows:
`1642941765: Bridge local.HomeAssistanttotv doing local SUBSCRIBE on topic <MQTT_PREFIX>/remoteapp/#
1642941765: Connecting bridge hisense (192.168.xxx.xxx:36669)
1642941765: Bridge HomeAssistanttotv sending CONNECT
1642941765: Socket error on client local.HomeAssistanttotv, disconnecting.`
Adding "log_type all" increased the log level, but didn't add anything useful.

I can successfully connect with MQTT Explorer using the files that "d3nd3 /Hisense-mqtt-keyfiles" has provided.
For example:   
"vidaa_support": "1",
  "country": "AUS",
  "language": "eng",
  "model_name": "55U62GAVT_0002",
  "tv_version": "V0000.01.00M.L1110"
So I am confident that the "bridge_certfile rcm_certchain_pem.cer and bridge_keyfile rcm_pem_privkey.pkcs8" are correct (if I omit one or the other in MQTT Explorer it fails to connect.)
Interestingly MQTT Explorer does not even require TLS or a valid username/password to connect (I'm assuming read-only).

So any ideas as to what might be going on?

Update: While writing this post to get all the information correct, I restarted the HiSense TV and it just started to work!
1643842818: Received CONNACK on connection local.HomeAssistanttotv.

So...at this point I think its a bug with HiSense and not HA. But I thought it might be worth reporting as, during my googling, I noticed others with the same errors in their MQTT logs.

Cheers Ben

**Comment by sehaas** [comment]
`bridge_keyfile` [requires a PEM file](https://mosquitto.org/man/mosquitto-conf-5.html#:~:text=bridge_keyfile). I don't think a `pkcs8` will work.

**Comment by bengAThome** [comment]
Hmm. Not sure then.
It seems to work though. MQTT doesn't complain when it parses it in HA, and I'm explicitly pointing to the file right now, not just asking it to look in the directory.
