### ISSUE TITLE
Installation instructions.

### ISSUE THREAD

**Issue by bengAThome** [sehaas/ha_hisense_tv#21]
Not sure why, but I had to copy the files into custom_components before I could add the integration.
Is that how its supposed to work?

**Comment by sehaas** [comment]
This repository can be installed via [HACS](https://hacs.xyz/) `Custom repositories`.
The only files you need to edit are from your MQTT broker.

**Comment by bengAThome** [comment]
Ahh, ok. I honestly did not know about HACS. When it was mentioned in another issue, I read it as the Home Assistant Community Add-ons store. Thanks for clearing that up, most of my HA has been with esphome.
I'd be happy to, redo my setup, document the steps and submit a doc update if that would help?
