### ISSUE TITLE
Unable to change topic

### ISSUE THREAD

**Issue by zacnut** [sehaas/ha_hisense_tv#22]
My TV needs the publish and subscription topic to be ">BLANK</remoteapp" and not "hisense/remoteapp"

Leaving subscription and publish topic blank during initial setup results in it defaulting to "hisense/remoteapp."
Setting the subscription and publish topic as '/' results in the topic to becoming  ">BLANK</>BLANK</remoteapp"

I have been able to get it partially working with NodeRed by bridging topics, but it will be a pain to do this for every topic back and forth. Setup like this was difficult enough.

My TV is up to date. I have seen another user with this issue solve this by updating their TV in the HA Hisense thread, but it did not solve my issue.

Could there be any solution?

Thanks

**Comment by sehaas** [comment]
Can you describe your setup in detail? Are you bridging your TV broker with the broker used by HA (usually Mosquitto)? If so, you can define the mapping there. See the readme.

The integration currently depends on such setup. If you leave the prefix empty, it will use the default `hisense`.

**Comment by zacnut** [comment]
Yes I have a working bridge outside of NodeRed. I only used NodeRed to take messages from the HA broker topic (for example):

hisense/remoteapp/tv/ui_service/HomeAssistant/actions/gettvstate

Then NodeRed will change the topic to:

/remoteapp/tv/ui_service/HomeAssistant/actions/gettvstate
(note the slash at the beginning)

This was so I could initially configure the integration... making the brigdge pointless plus i would need to do this with every topic back and forth...

Is there any way we can have the publish and subscription topic be left blank and not default to hisense?

Or how would I define the mapping?

My bridge conf:

connection hisensemqtt
address 192.168.1.11:36669
username hisenseservice
password multimqttservice
clientid HomeAssistant
bridge_cafile /ssl/hisense.crt
bridge_insecure true
bridge_tls_version tlsv1.2
try_private false
start_type automatic
topic /remoteapp/# both 0 ""

**Comment by zacnut** [comment]
I have fixed my issue with Mosquito topic bridging.

connection hisensemqtt
address 192.168.1.11:36669
username hisenseservice
password multimqttservice
clientid HomeAssistant
bridge_cafile /ssl/hisense.crt
bridge_insecure true
bridge_tls_version tlsv1.2
try_private false
start_type automatic
topic remoteapp/# in 0 hisense/ /
topic # out 0 hisense/ /
