### ISSUE TITLE
Enumerate/launch apps

### ISSUE THREAD

**Issue by YodaDaCoda** [sehaas/ha_hisense_tv#23]
It'd be nice to be able to view the list of apps, and launch an app by selecting one from a list.

Enumerate apps:
publish:
`/remoteapp/tv/ui_service/HomeAssistant/actions/applist`
subscribe:
`/remoteapp/mobile/HomeAssistant/ui_service/data/applist`

Launch app:
publish:
`/remoteapp/tv/ui_service/HomeAssistant/actions/launchapp`
send JSON payload including `name` and `url`
E.g. launch built-in Youtube app:
`{"name": "Youtube", "url": "youtube"}`
E.g. launch Plex app installed from market:
`{"name": "Plex", "url": "https://app.plex.tv/tv-vidaa"}`

**Comment by sehaas** [comment]
It's already possible via the `MediaPlayer` entity.
<img width="810" alt="Screenshot 2022-03-06 at 9 50 55 AM" src="https://user-images.githubusercontent.com/283482/156916026-29efcd47-cabd-461c-a5c8-e5a92c74eefb.png">
<img width="810" alt="Screenshot 2022-03-06 at 9 51 10 AM" src="https://user-images.githubusercontent.com/283482/156915981-7da7dd98-abab-4abc-88c4-6bb6a14a4110.png">
<img width="810" alt="Screenshot 2022-03-06 at 9 51 31 AM" src="https://user-images.githubusercontent.com/283482/156915985-9cc25fcc-bee0-4e70-879e-fa9b02be009a.png">
