### ISSUE TITLE
Cannot change source

### ISSUE THREAD

**Issue by UncleLeoTheDad** [sehaas/ha_hisense_tv#25]
Hi again!

I am able to use this integration to control on/off via node-red fine, but when I try to change the source, nothing happens.  Here is what my node-red command looks like:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/141352/156935023-9781a7ff-ba3f-4399-9415-f420fcbc0b0c.png">

When I try the same via the dev tools I get the same result:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/141352/156935070-a9fe4a37-8df8-4497-9e63-d554d5963531.png">

When I watch the MQTT via a tool, I do notice that the action published is different from the one that the remote app publishes.  It only includes sourceID and not sourcename.  The remote app DOES work:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/141352/156935153-d9dc8f88-ab5f-4c17-a2f4-be42035f51e5.png">

Here is the overall state of the TV:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/141352/156935191-3c2f36f3-04e0-4568-aaf9-79b40f1abe0d.png">

Anything obvious that I am doing wrong?

Thanks!

**Comment by sehaas** [comment]
Looks like some models behave different. Mine was happy with only the `sourceid`. Please try the new version.

**Comment by peteshoard** [comment]
Any updates on this one? i don't get any sources apart from App
