### ISSUE TITLE
Cannot input PIN on setup: async_pin_needed

### ISSUE THREAD

**Issue by de68guard** [sehaas/ha_hisense_tv#28]
When I try  the first setup and the TV is turned on. The integration requires a PIN code from the TV. The TV shows the PIN, however the integration doesn't provide a way to input the pin. would it need to be put into a config file?
Logs 
022-05-01 18:08:53 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] async_step_user INFO None
2022-05-01 18:10:43 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] async_step_user NOT task_mqtt
2022-05-01 18:10:43 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] _async_pin_needed

**Comment by sehaas** [comment]
Which HA version do you use? Can you provide screenshots of the config flow?
You should be able to enter the PIN during the config flow. It's only needed one time, so it's not stored in any config afterwards.

**Comment by de68guard** [comment]
Thanks for your reply

Versions:
Host Operating System | Home Assistant OS 7.6
Supervisor Version | supervisor-2022.05.0
Home Assistant Core: 2022.5.2

**Mosquitto broker mosquitto.conf:**
onnection hisense
address 10.254.254.10:36669
username hisenseservice
password  multimqttservice
clientid HomeAssistant
bridge_tls_version tlsv1.2
bridge_cafile /share/mosquitto/hisense_ca.pem
bridge_certfile /share/mosquitto/hisense_client.pem
bridge_keyfile /share/mosquitto/hisense_client.key
bridge_insecure true
start_type automatic
try_private true
topic /remoteapp/# both 0 hisense ""         

**Config Flow:**

![Screenshot from 2022-05-07 14-21-16](https://user-images.githubusercontent.com/102453477/167238346-c50bc63e-c070-4a3b-bb6f-fe8652e5765e.png)

![Screenshot from 2022-05-07 14-21-53](https://user-images.githubusercontent.com/102453477/167238343-4a247396-30be-415c-b6ed-e81a0c7e4f61.png)
![Screenshot from 2022-05-07 14-21-49](https://user-images.githubusercontent.com/102453477/167238344-17c73c1d-13a7-40d0-9c59-b8a36ffb756d.png)

**Comment by sehaas** [comment]
sounds like https://github.com/sehaas/ha_hisense_tv/issues/24#issuecomment-1094059067

**Comment by epictechlab** [comment]
I have the same problem as @de68guard. I have also tried different browser but can't the pin field on HA.

**Comment by sehaas** [comment]
My guess is, that it's a timing issue. I published a new version with more debug logging.
You can change the log level for just one component like:
```
logger:
  default: info
  logs:
    custom_components.hisense_tv: debug
```

**Comment by epictechlab** [comment]
Okay thanks.
I've added this to my Config.yaml, how to get this config_flow Logs?

**Comment by de68guard** [comment]
Hi

Thanks for pointing to https://github.com/sehaas/ha_hisense_tv/issues/24#issuecomment-1094059067, I did notice that issue before and tested in firefox and Chromium (both in linux), but as suggested I have also tested the same in Chrome and Edge (now in Windows 10) with the same results.

I must be missing something basic

logger already as suggested
logger:
  default: info
  logs:
    custom_components.hisense_tv: debug

Logs the following messages:
2022-05-11 14:23:22 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] async_step_user INFO None
2022-05-11 14:23:47 INFO (Thread-3) [homeassistant.components.mqtt] Connected to MQTT server core-mosquitto:1883 (0)
2022-05-11 14:24:13 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] async_step_user NOT task_mqtt
2022-05-11 14:24:14 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] _async_pin_needed

I have success with https://github.com/newAM/hisensetv:
python3.8 -m pip install hisensetv
hisensetv 10.254.254.10 --authorize
Please enter the 4-digit code: 7815

Also I have good responses with MQTT-explorer directly to TV with the same certs and over the Bridge in Hass.

My next test would be try use HACS that I have not used before.

Thanks

**Comment by sehaas** [comment]
Please use version `22.05.09`, your log output is from an older version.
Your MQTT setup should be OK, as your TV does display the PIN. I suspect the problem during the HA config flow and async calls.

**Comment by de68guard** [comment]
Thanks

forgot to deploy the new downloaded version:
Logs /config/home-assistant.log (ssh) also located http://<your HA>:8123/config/logs [@epicteclab ](https://github.com/epictechlab)
2022-05-11 18:02:46 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] async_step_user - user_input is None
2022-05-11 18:03:45 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] async_step_user - set task_mqtt
2022-05-11 18:03:45 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] _check_authentication - publish gettvstate
2022-05-11 18:03:45 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] _check_authentication - publish sourcelist
2022-05-11 18:03:45 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] _async_pin_needed
2022-05-11 18:03:45 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] _unsubscribe
2022-05-11 18:03:45 DEBUG (MainThread) [custom_components.hisense_tv.config_flow] async_step_user - task_auth is False

**Comment by sehaas** [comment]
Thanks for the logs. Right after your last entry, the config flow would call the next step `return self.async_show_progress_done(next_step_id="auth")`. But it looks like `async_step_auth` is never called.
Unfortunately it always works for me, so I can't reproduce/debug your behaviour.
These API calls are provided by HA and I don't know where to start looking for the problem.

**Comment by thesebastianf** [comment]
I have the same issue. Anything we can Help to find the root cause?
I use currently use the WiFi from the Hisense. I could Test LAN.


Edit:
After Reading 24 I Used another Laptop ...and voila I could enter a Pin.

**Comment by de68guard** [comment]
> Thanks for the logs. Right after your last entry, the config flow would call the next step `return self.async_show_progress_done(next_step_id="auth")`. But it looks like `async_step_auth` is never called. Unfortunately it always works for me, so I can't reproduce/debug your behaviour. These API calls are provided by HA and I don't know where to start looking for the problem.

Thanks for the help so far, I have been trying a couple of debug attempts including trace the Mosquitto bridge, I cann see the issue is in the HA API that try to follow after self.async_show_progress_done but no luck

I would try install a mosquitto bridge in a VM and use it instead of the addon docker, 

if the same issue maybe can I authorise with the python from https://github.com/newAM/hisensetv?

Last I would try reinstall everything in a dedicated HASS instance.

**Comment by de68guard** [comment]
@sehaas Much appreciated, finally it works. 
I had to use a newer device (laptop) running Chrome (my lab devices are all a bit old).
I try to many things and was focusing in the HASS  instance using the clue of timing issues from https://community.home-assistant.io/t/hisense-tv-control/97638/253, but at the end it was my devices were to old (timing maybe).

**Comment by goobags** [comment]
@de68guard any more specifics on the 'newer' device fixing the problem? I am on an almost new MacBook and the problem exists. I have tried Safari and Chrome on it but the same problem. I only have access to older MacOS devices or Raspberry Pi's (tried the Pi with Chromium - no luck)

**Comment by de68guard** [comment]
The newer devices that worked both are Windows, one W10 and the other W11, and both are Windows11 capable, maybe that is the clue, I haven't played further.
