### ISSUE TITLE
Channel change

### ISSUE THREAD

**Issue by wifi75** [sehaas/ha_hisense_tv#3]
hi, I would like to create a scene in HA, which at 07 in the morning the TV turns on and positions itself on channel number 5.

I don't understand how to change the channel, I was able to turn it on, switch to the TV source but not change the channel and set the audio level.

how I can do it?

**Comment by sehaas** [comment]
Hi,
it's not supported at the moment. You can change source, channel & apps via the mediaplayer UI. But it should be straightforward to implement it.
Two possible solutions:
1. mimic a remote control and send the number keys for the channel (https://github.com/Krazy998/mqtt-hisensetv#content-interaction)
2. select the channel from the channel list and switch directly. Like it is done in `media_player.py`
https://github.com/sehaas/ha_hisense_tv/blob/1fe4b698f0455f470d71dbe3283ea054da71684a/custom_components/hisense_tv/media_player.py#L609

Pull request are welcome.
