### ISSUE TITLE
TV shows as on when is off

### ISSUE THREAD

**Issue by Piti8576** [sehaas/ha_hisense_tv#35]
When the tv is off the integration show it as on.
When TV is off and i restart HA the TV show as off correct.

When TV is on all display fine and correct (input, channel .....).

But without restart HA is show permanent as on.

**Comment by NeeeeB** [comment]
I'm in the same boat.
Addon is not working anymore.

This is what I get in the mosquitto log : 
![image](https://user-images.githubusercontent.com/12588210/190613709-dd071fdc-6505-475c-b2ea-7fb830afc278.png)

setup infos : 
![image](https://user-images.githubusercontent.com/12588210/190613819-b2fda77e-d5de-47bb-a2b0-6e33f2e45929.png)

![image](https://user-images.githubusercontent.com/12588210/190613937-a726e772-fafe-4f8c-b8af-1e69d29e5f27.png)

@sehaas could you have a look please ?

**Comment by sehaas** [comment]
> When the tv is off the integration show it as on. When TV is off and i restart HA the TV show as off correct.
> 
> When TV is on all display fine and correct (input, channel .....).
> 
> But without restart HA is show permanent as on.

Sounds like your  MQTT broker has retained flags set for some of the Hisense topics. Try to reset them.

**Comment by sehaas** [comment]
> I'm in the same boat. Addon is not working anymore.
> 
> This is what I get in the mosquitto log : ![image](https://user-images.githubusercontent.com/12588210/190613709-dd071fdc-6505-475c-b2ea-7fb830afc278.png)
> 
> setup infos : ![image](https://user-images.githubusercontent.com/12588210/190613819-b2fda77e-d5de-47bb-a2b0-6e33f2e45929.png)
> 
> ![image](https://user-images.githubusercontent.com/12588210/190613937-a726e772-fafe-4f8c-b8af-1e69d29e5f27.png)
> 
> @sehaas could you have a look please ?

Not sure if your screens are related to the original issue. But you have to check your MQTT broker as well. The log clearly says, that the connection isn't working. The integration won't work if the underlying MQTT setup isn't working.

**Comment by NeeeeB** [comment]
Yeah sorry for the inconvenience, it seems the problem was Somewhere else and fixed by itself. It works now without me doing anything...
Really sorry for bothering you.
Thanks
