### ISSUE TITLE
Sources - Only 'App' Available

### ISSUE THREAD

**Issue by peteshoard** [sehaas/ha_hisense_tv#39]
Noticed that only the App source appears available on my sources list - looks like you may have identified and are working on this issue - any workarounds in the meanwhile? i have tried the media.sources service but cant pass plain text

Thanks

**Comment by sehaas** [comment]
What does `<prefix>/remoteapp/mobile/HomeAssistant/platform_service/data/getchannellistinfo` return if you open the media browser?
What kind of input source do you expect? I tested the integration with a LNB/satellite dish connected to the TV.

**Comment by peteshoard** [comment]
Channel lists work great, no problem there, thanks - its the sources. 
This topic should populate the source dropndown?
hisensetv/remoteapp/mobile/HomeAssistant/ui_service/data/sourcelist - is what i think it should pull, but doent - below is the 

value in that topic:

[{"sourceid":"0","sourcename":"TV","displayname":"tele","is_signal":"1","is_lock":"0","hotel_mode":"0"},{"sourceid":"3","sourcename":"HDMI 1","displayname":"Kindle","is_signal":"1","is_lock":"0","hotel_mode":"0"},{"sourceid":"5","sourcename":"HDMI 3","displayname":"CCTV","is_signal":"1","is_lock":"0","hotel_mode":"0"},{"sourceid":"4","sourcename":"HDMI 2","displayname":"HDMI 2","is_signal":"0","is_lock":"0","hotel_mode":"0"},{"sourceid":"1","sourcename":"AV","displayname":"AV","is_signal":"0","is_lock":"0","hotel_mode":"0"}]

and all i get in the drop down is 'App' as per the image

![image](https://user-images.githubusercontent.com/54681089/210840530-b110414f-b77f-42f5-b7c0-82088227be31.png)

**Comment by sehaas** [comment]
The values look fine. Please check your logs for `_message_received_sourcelist - skip retained message` or check if the MQTT message from `hisensetv/remoteapp/mobile/HomeAssistant/ui_service/data/sourcelist` has the `retained` flag set.

If this is the case, you have to unset/delete the message from the TV broker and/or from the HA broker. This can be done with tools like the MQTT Explorer.
