### ISSUE TITLE
Switch status not updated after power cycle of the TV

### ISSUE THREAD

**Issue by NeeeeB** [sehaas/ha_hisense_tv#4]
Integration is installed, but switch status is OFF (even with the TV ON) as long as I don't run the app once on my phone.
Then, the switch status is updated in HA and reflects the TV state (ON).
I can then kill the app on my phone and play with the integration (volume, channels and so on...)
If I switch OFF the TV, the switch in HA is updated to OFF.
But then I can no longer switch ON the TV from HA.
I need to use the TV remote to switch it ON.
And the switch in HA stays OFF, until I run the app on my phone again.
It is as if the TV broker needs to be activated by the app to work properly...

**Comment by gogui63** [comment]
Hey @NeeeeB i've same issue 

I need to restart my mobile app to "wake UP" this integration

**Comment by sehaas** [comment]
The integration uses WakeOnLan to turn the TV on. Is it activated on your TV? How is your TV connected? LAN or WiFi?

The TV broker isn't running all the time. Mine shuts down sometimes after I switch off the TV, but gets active again when the TV gets turned on. Then the current state is sent out which toggles the state in HA.

Tbh I don't know how the App turns the TV on.

**Comment by NeeeeB** [comment]
Found the culprit :
TV fastboot must be enabled for the integration to work properly...
I you disable Fastboot, broker does not connect when you switch on the TV.

**Comment by sehaas** [comment]
Thanks for the info. I didn't know or change this setting, but I can confirm it's on for my TV.

**Comment by mikhail5555** [comment]
I am encountering about the same problem, when switching the TV from 'no-power' state to on, it either doesn't connect fast enough with the broker or just never broadcasts that it turned on.
