### ISSUE TITLE
Can anyone explain how this works?

### ISSUE THREAD

**Issue by meneer-code** [sehaas/ha_hisense_tv#40]
I have an idea that the readme assumes that the user should know a lot of things... however I'm really struggling.

Can it please be updated with relevant information? Or  maybe send some resources on how to get started?

**Comment by sehaas** [comment]
The setup isn't as trivial as installing any other HA/HACS integrations, as you need to set up the MQTT bridge manually. All the relevant information should be in this repository (except the certificates for legal reasons).

If you have a specific question maybe someone can help you.

**Comment by peteshoard** [comment]
Rather than setup an MQTT bridge i found it easier to connect the brokers using NodeRed with simple text change nodes to specify the relevant topic changes

**Comment by meneer-code** [comment]
Hey @peteshoard this seems like something I could do. Are you perhaps able to point me to the steps on how you did this, and provide your flow as an example?

A simple ON/OFF is all I need for now.

I'm happy to format and summarise the steps for this method. I've spent quite some time trying to figure this out on https://community.home-assistant.io/t/hisense-tv-control/97638/1

**Comment by peteshoard** [comment]
Hey Meneer, happy to help,

Node red config is below, you should be able to simply copy/paste:

![fred tm](https://user-images.githubusercontent.com/54681089/212546722-2035d56a-cec7-4676-88ca-532d4a9ea7ca.png)


[
    {
        "id": "9eba024d59a0f1ae",
        "type": "mqtt in",
        "z": "6c181d07.c5c534",
        "name": "",
        "topic": "/remoteapp/#",
        "qos": "2",
        "datatype": "auto",
        "broker": "d2bb5c79f9ddff97",
        "nl": false,
        "rap": true,
        "rh": 0,
        "inputs": 0,
        "x": 170,
        "y": 480,
        "wires": [
            [
                "b481286f2ba0beaa"
            ]
        ]
    },
    {
        "id": "f368aa75680e3b90",
        "type": "mqtt out",
        "z": "6c181d07.c5c534",
        "name": "",
        "topic": "",
        "qos": "",
        "retain": "",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "345fe35d.840b8c",
        "x": 540,
        "y": 480,
        "wires": []
    },
    {
        "id": "b481286f2ba0beaa",
        "type": "change",
        "z": "6c181d07.c5c534",
        "name": "",
        "rules": [
            {
                "t": "change",
                "p": "topic",
                "pt": "msg",
                "from": "/remoteapp",
                "fromt": "str",
                "to": "hisensetv/remoteapp",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 360,
        "y": 480,
        "wires": [
            [
                "f368aa75680e3b90"
            ]
        ]
    },
    {
        "id": "2b860305a298a068",
        "type": "mqtt in",
        "z": "6c181d07.c5c534",
        "name": "",
        "topic": "hisenseresp/#",
        "qos": "2",
        "datatype": "auto",
        "broker": "345fe35d.840b8c",
        "nl": false,
        "rap": true,
        "rh": 0,
        "inputs": 0,
        "x": 170,
        "y": 440,
        "wires": [
            [
                "e353129f689ef24b"
            ]
        ]
    },
    {
        "id": "578e89a13681dde6",
        "type": "mqtt out",
        "z": "6c181d07.c5c534",
        "name": "",
        "topic": "",
        "qos": "",
        "retain": "",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "d2bb5c79f9ddff97",
        "x": 550,
        "y": 440,
        "wires": []
    },
    {
        "id": "e353129f689ef24b",
        "type": "change",
        "z": "6c181d07.c5c534",
        "name": "",
        "rules": [
            {
                "t": "change",
                "p": "topic",
                "pt": "msg",
                "from": "hisenseresp",
                "fromt": "str",
                "to": "",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 360,
        "y": 440,
        "wires": [
            [
                "578e89a13681dde6"
            ]
        ]
    },
    {
        "id": "d2bb5c79f9ddff97",
        "type": "mqtt-broker",
        "name": "",
        "broker": "192.168.2.168",
        "port": "36669",
        "clientid": "",
        "autoConnect": true,
        "usetls": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "willMsg": {},
        "sessionExpiry": ""
    },
    {
        "id": "345fe35d.840b8c",
        "type": "mqtt-broker",
        "name": "commandpi",
        "broker": "192.168.2.252",
        "port": "1883",
        "clientid": "",
        "autoConnect": true,
        "usetls": false,
        "compatmode": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "willMsg": {},
        "sessionExpiry": ""
    }
]

1. you must have a MQTT broker in your network.
2. you must have your broker and the hisense tv configured as MQTT servers in your node red config
3. your Hisense MQTT settings need to reflect the below topics: 
![fred2 tm](https://user-images.githubusercontent.com/54681089/212547029-73926996-3c6a-4238-8b2e-ec2dbc96702a.png)
