### ISSUE TITLE
wheel spins nonstop during integration.

### ISSUE THREAD

**Issue by tung256** [sehaas/ha_hisense_tv#42]
i just got a Hisense qled TV.

i gave the integration the TV's ip address and mac.  now it's just spinning..   any idea?
![image](https://user-images.githubusercontent.com/37672036/210190475-12ac9ff7-22db-4984-8c6d-1f68b13a2697.png)

**Comment by SolarSciencePup** [comment]
Same here

**Comment by tim-devel** [comment]
Me too.  I can't see how to debug, there are no errors or messages in the logs.  The pin screen comes up on the TV but the when is spinning on home Assistant so I can't type it in

**Comment by sehaas** [comment]
Did you setup the MQTT bridge and does your HA MQTT broker receive messages? Does the PIN appear on the TV?

If yes - you triggered a behaviour reported multiple times already. Some users reported, that they fixed it by using another browser. See #28. Unfortunately I wasn't able to reproduce the problem with my HA setup. To enable a more detailed logging you can extend your HA config like:
```yaml
logger:
  default: info # maybe existing
  logs:
    custom_components.hisense_tv: debug # new config
```

If no - please fix the bridge first.

**Comment by SolarSciencePup** [comment]
Pin does not

**Comment by tung256** [comment]
how to set up MQTT bridge? this part was not fully explained in your instruction  :(
thanks for helping us out! strangely no one has ever done a youtube guide too

**Comment by toddstar** [comment]
> how to set up MQTT bridge? this part was not fully explained in your instruction :( thanks for helping us out! strangely no one has ever done a youtube guide too

assuming you're using the HA mosquitto addon then you need to create a config file under '/share/mosquitto/' i.e. something like '/share/mosquitto/hisense.conf' which has the connection details [which in my case is](https://user-images.githubusercontent.com/22575856/212388044-c9265f7f-bd26-4dd2-86ac-09fbb8e4e7b2.png)

```
connection Hisense
address 192.168.0.16:36669
remote_username hisenseservice
remote_password multimqttservice
cleansession false
clientid HomeAssistant
try_private false
topic /remoteapp/# both 0 hisense
```

**Comment by tung256** [comment]
> > how to set up MQTT bridge? this part was not fully explained in your instruction :( thanks for helping us out! strangely no one has ever done a youtube guide too
> 
> assuming you're using the HA mosquitto addon then you need to create a config file under '/share/mosquitto/' i.e. something like '/share/mosquitto/hisense.conf' which has the connection details [which in my case is](https://user-images.githubusercontent.com/22575856/212388044-c9265f7f-bd26-4dd2-86ac-09fbb8e4e7b2.png)
> 
yes, i use Mosquitto.
so i have my hisense.conf here:
![image](https://user-images.githubusercontent.com/37672036/213727905-ff5bc1a1-46aa-4ae3-b3c1-022607323a4c.png)

i tried your code as seen here:
![image](https://user-images.githubusercontent.com/37672036/213728009-bfd4f8d4-2562-42b2-8342-85462e2bfd69.png)

i tried using the default github code here:
![image](https://user-images.githubusercontent.com/37672036/213728115-f67d5a15-b7a5-4f6d-b8f1-5b6c8fe27ff8.png)


neither worked.  the wheel still spins as before.  
just to be sure, i also added this user n pass into my HA:
username hisenseservice
password  multimqttservice

**Comment by toddstar** [comment]
@tung256 if my connection code doesn't work then you'll probably have a TV that requires certificates to connect; you need to actually download these and add them to your system, just adding `bridge_tls_version tlsv1.2
bridge_cafile hisense_ca.pem.....` to the connection code won't do anything. 

Suggest you search through the forum post https://community.home-assistant.io/t/hisense-tv-control for "certs" or "keys" (https://community.home-assistant.io/t/hisense-tv-control/97638/269 looks good post to follow to me. but my TV doesn't require certs so can't confirm)
