### ISSUE TITLE
Change actions/picturesetting to actions/gettvstate ?

### ISSUE THREAD

**Issue by toddstar** [sehaas/ha_hisense_tv#44]
My hisense doesn't output any picture settings (is a couple years old) so the 5 minute polling of the state doesn't work as the actions/picturesetting is just ignored. Would it be possible to change to actions/gettvstate as that seems to be a standard function on all modals from searching through forums/posts on hisense tv about mqtt (or code it so that if actions/picturesetting doesnt return data so the sensor parameters are mainly blank*, then have actions/gettvstate be a fallback)

 *Screenshot of what i get on the sensor - https://user-images.githubusercontent.com/22575856/212385144-102babc1-f0af-4503-a3fe-4c79d66a6fa3.jpg

add PR for basic change from one to the other, may attempt PR for second fallback option but outside of my tinkering comfort level so may take a while

**Comment by sehaas** [comment]
Sorry, but your PR will break the sensor for everyone. If your TV does not provide the picture settings, what are you using the sensor for? Maybe there is another solution to achieve your requirements?

**Comment by toddstar** [comment]
> Sorry, but your PR will break the sensor for everyone. If your TV does not provide the picture settings, what are you using the sensor for? Maybe there is another solution to achieve your requirements?

The sensor in my setup provides nothing, I'm just using the Media player for a bit of TV control but mainly in connection with https://github.com/bramstroker/homeassistant-powercalc to get an estimate wattage for completely off (unavailable), standby (off) & on.  

The issue I running into when the socket gets turned on (have a smart plug for TV & Sky Q box as the later basically doesnt have a standby mode) and the TV gets turned on outside of HA (physical remote or by the sky box being turned on) the media player state doesn't change unless I manually input a change on the TV (i.e. changed the volume).

If the PR is gonna break the code then can fall back into my orginal thought of just having an automation that publishes the gettvstate mqtt command in HA 30/60 seconds after the plug socket changes state, that repeats until the Media player state changes to on
