### ISSUE TITLE
Feature request: please support mosquitto as well

### ISSUE THREAD

**Issue by MaxRower** [sehaas/ha_hisense_tv#47]
Tried it, with a bridge to the tv configured in mosquitto, but it did not work.

**Comment by nepozs** [comment]
It supports Mosquitto, but there is NO possibility to work without bridge configuration in Mosquitto (as TV has own MQTT broker, and HA supports only 1 MQTT broker).

Quick tutorial in polish language (you can use some online translator):
https://forum.arturhome.pl/t/telewizor-hisense-z-systemem-vidaa/7985

**Comment by MaxRower** [comment]
Sure, I have mosquitto (not the integrated mqtt broker, as I am using zigbee2mqtt) with a bridge to the TV running, everything works fine, I can do mosquitto_pub and _sub correctly. But when I start the Hisense integration, it displays a message that the bridge is being started, and afterwards displays a 500 internal server error. So it tries to setup a bridge in the integrated mqtt broker, and not using my preconfigured bridge in mosquitto.

**Comment by MaxRower** [comment]
To clarify, I am using mosquitto from the standard ubuntu 22.04 repo, not an addon. Home Assistant is installed as a snap.
