### ISSUE TITLE
bootloop

### ISSUE THREAD

**Issue by bobdivx** [sehaas/ha_hisense_tv#55]
Hello, I'm trying to add my hisense tv but after adding the requested information, Ha runs in a loop. yet I manage to connect in mqtt via Mqtt explorer.
No information in the logs

**Comment by mar-techsoft** [comment]
Same issue, any updates?

**Comment by sehaas** [comment]
This repo isn't maintained at the moment since I don't have a setup where I could test changes myself.

Feel free to contribute. I'll try to review and merge changes.

**Comment by mar-techsoft** [comment]
Alright, will do if I find a solution.
