### ISSUE TITLE
problems connecting to mqtt

### ISSUE THREAD

**Issue by zamzon** [sehaas/ha_hisense_tv#56]
I can't get this to work on my 100U7KQ Hisense TV form 2023

If I connect to the TV from my MQTT Explorer with the following details it wont connect.
are there any changes on new hisense tv´s mine uses VIDAA as operation system.
I tryed with ectyption on/off and Validate certificate on/off with on luck 

![Udklip](https://github.com/sehaas/ha_hisense_tv/assets/12298056/f44e80ae-f8d4-4c02-ab71-9d1f88e56b65)

**Comment by LeoKlaus** [comment]
Hisense made the login flow a lot more complicated with the 2023 models, see krazy998/mqtt-hisensetv#14

This integration _should_ work with some modifications, but it would have to periodically refresh its access token.

**Comment by zamzon** [comment]
I have no idea how to fix this, so I'm hoping for a finish solution with a guide 😊
