### ISSUE TITLE
Manual configuration instruction?

### ISSUE THREAD

**Issue by Rheinmetallskorpion** [sehaas/ha_hisense_tv#7]
README says it can be configured using Home Assistant UI. However, neither can it be found on HACS nor the official integration. Manually adding the repo to HACS will not result in successful downloads. Is there any way to manually configure this before the UI becomes available?

**Comment by Rheinmetallskorpion** [comment]
Plus, I'm getting a fatal error. I have username and password configured like this according to another repo. 
`2021-12-04 05:13:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 170, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 224, in _async_init
result = await self._async_handle_step(flow, flow.init_step, data, init_done)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/config_flow.py", line 216, in async_step_ssdp
if _is_ignored_device(discovery_info):
File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/config_flow.py", line 477, in _is_ignored_device
manufacturer = discovery_info.get(ssdp.ATTR_UPNP_MANUFACTURER, "").lower()
AttributeError: 'NoneType' object has no attribute 'lower'`

**Comment by Rheinmetallskorpion** [comment]
And I just found the broker won't start after the configuration. Do I need extra programs or files to complete the bridge setup? Thanks!

**Comment by Actpohomoc** [comment]
I would like to try this integration too on my U8QF.

**Comment by sehaas** [comment]
> And I just found the broker won't start after the configuration. Do I need extra programs or files to complete the bridge setup? Thanks!

Please verify that your HA broker is connected to your TV. You can use mqttexplorer or other tools.
The mqtt setup from the readme reflects my setup. I don't know yours, so please verify that the mqtt brokers are connected correctly.

I don't see a direct connect between this component and the stacktrace you provided. Isn't it more likely the `dlna_dmr`?

**Comment by sehaas** [comment]
> I would like to try this integration too on my U8QF.

I don't know this model and if it also comes with an mqtt broker. You could scan the TV's ports and see if a broker is running. If so, you could try to adapt the setup for your TV.

**Comment by Rheinmetallskorpion** [comment]
> > And I just found the broker won't start after the configuration. Do I need extra programs or files to complete the bridge setup? Thanks!
> 
> Please verify that your HA broker is connected to your TV. You can use mqttexplorer or other tools. The mqtt setup from the readme reflects my setup. I don't know yours, so please verify that the mqtt brokers are connected correctly.
> 
> I don't see a direct connect between this component and the stacktrace you provided. Isn't it more likely the `dlna_dmr`?

I’m pretty sure they’re not connected because after implementing the configuration to the broker on rpi, the broker doesn’t even start. Calling system service to start/stop is also unresponsive. The broker would work normally after reverting the config file.

**Comment by sehaas** [comment]
Are your CA, cert and key files accessible for the broker? Correct path, correct file permission, ...
What does the broker log while starting up? I'm sure there will be an error log.

**Comment by Rheinmetallskorpion** [comment]
The .key and .pen file are both in /etc/mosquitto, sharing the same directory as mosquitto.conf. It used to have rwx for owner but I have just applied chmod +r to it so it should be readable by anyone. I’ll give it a try and see what happens. 
Also, since the TV doesn’t connect to Wi-Fi when powered off, will it be any issue if the rpi broker loses the connection to the TV one? Thanks a lot!

**Comment by Rheinmetallskorpion** [comment]
> > And I just found the broker won't start after the configuration. Do I need extra programs or files to complete the bridge setup? Thanks!
> 
> Please verify that your HA broker is connected to your TV. You can use mqttexplorer or other tools. The mqtt setup from the readme reflects my setup. I don't know yours, so please verify that the mqtt brokers are connected correctly.
> 
> I don't see a direct connect between this component and the stacktrace you provided. Isn't it more likely the `dlna_dmr`?

Concerning the log, it only appeared when I start HA with this component, so I thought that dlna_dmr was a dependency of this component. But if it's not, I'll retry and see what the latest log will be.

**Comment by Rheinmetallskorpion** [comment]
After retrying with new permission, the mosquitto broker on rpi can run. The log shows it keeps connecting to hisense but never shows success. The same dlna_dmr error occurs too. 

I have scanned the 36669 port on my TV using nmap and it shows it's an open TCP port. I guess my TV does speak mqtt but something must be off.

**Comment by dustinlocke** [comment]
I'm also not able to find a way to install via UI. Looks awesome, though. Excited to test it out.

**Comment by nepozs** [comment]
> I guess my TV does speak mqtt but something must be off. 

1. It must be Vidaa line model.

2. It must be able to be controlled by this mobile app:
https://play.google.com/store/apps/details?id=com.universal.remote.ms
https://apps.apple.com/us/app/remotenow/id1301866548

3. It could be related to Menu items (but I didn't really find a dependency):

Settings -> Support  -> Disclaimer and Privacy  -> EULA (?)
Settings -> Support  -> Disclaimer and Privacy  -> Remote Management (?)
Settings -> Support  -> Remote Control Service (?)

Settings -> Advanced Settings -> Fast Power On (better is disabled, IMHO it is unrelated, but in some cases people say "it must be disabled")

below are unrelated to MQTT but ability to Power On depends on WOL
Settings -> Network -> Wake on WLAN (depends on connection type)
Settings -> Network -> Wake on LAN (depends on connection type, preferred)

**Comment by 628426** [comment]
> I'm also not able to find a way to install via UI. Looks awesome, though. Excited to test it out.

@dustinlocke You can use the Custom Repository button in the top right of the HACS Integrations screen to add this repository.

High level steps

Add repository
Make sure Mosquitto Add-on is installed from core add-on store
Then install HISense MQQT Bridge
Then install HiSense TV integration

**Comment by andreac** [comment]
> > I'm also not able to find a way to install via UI. Looks awesome, though. Excited to test it out.
> 
> @dustinlocke You can use the Custom Repository button in the top right of the HACS Integrations screen to add this repository.
> 
> High level steps
> 
> Add repository Make sure Mosquitto Add-on is installed from core add-on store Then install HISense MQQT Bridge Then install HiSense TV integration

Hi, I added the repo and restarted HA, but in config->integration i'm not able to find hisense tv. What i'm missing?
