### ISSUE TITLE
Unable to complete setup?

### ISSUE THREAD

**Issue by tungmeister** [sehaas/ha_hisense_tv#8]
I believe I've got everything setup correctly. 

here's my config and all the certs are present:

```
connection hisensemqtt
address 10.0.0.30:36669
username hisenseservice
password multimqttservice
clientid HomeAssistant
bridge_cafile /share/mosquitto/ssl/hisense.crt
bridge_certfile /share/mosquitto/ssl/rcm_certchain_pem.cer
bridge_keyfile /share/mosquitto/ssl/rcm_pem_privkey.pkcs8
bridge_insecure true
bridge_tls_version tlsv1.2
try_private false
start_type automatic
topic /remoteapp/# both 0 hisense ""
```
here's what I see in the mosquitto logs:

![image](https://user-images.githubusercontent.com/127809/145202859-bb9470ce-04bd-464b-ba63-c0d82907de40.png)

and it appears to be connected:

![image](https://user-images.githubusercontent.com/127809/145204752-2c3141de-a7d9-48b7-b3da-3998e229ff7b.png)

but all I get in the config in HA is this:

![image](https://user-images.githubusercontent.com/127809/145203637-bc1a8a7c-b6dc-4a99-acac-b7f5b5152c92.png)

I'm unable to proceed from this point.

**Comment by sehaas** [comment]
`10.0.0.30` is your TV?
Try to connect to your HA mqtt broker instead and inspect if you get messages from the TV.

**Comment by tungmeister** [comment]
it is, As I'm up in my office setting this up I hadn't realised that prompt was for the on screen code - I'd just reread through the thread and saw someone mention the code, ran downstairs and it was showing on screen. I'm now paired successfully :joy:
Are you still actively developing this out of interest? Might be worth adding a string to that prompt stating it's for the on-screen code unless it's mentioned in the readme and I just missed it.

**Comment by sehaas** [comment]
Good to hear.
The current state fits my needs, but of course I'll accept pull request for new features or burgfixes.

Can I close this issue as your pairing was successful?
